# Generated by Django 4.2 on 2023-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_temperaturesensor_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.BooleanField()),
            ],
        ),
    ]
