# Generated by Django 4.1.7 on 2023-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fanstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidityValue', models.SmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightValue', models.SmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PirSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pirState', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fanstate',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2012-04-23 18:25:43.511000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperaturesensor',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fanstate',
            name='IsActive',
            field=models.SmallIntegerField(),
        ),
    ]
